language: node_js
node_js: 7
script:
 — echo "Deploy!!"
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy — project sapir-coffe — token 1/cQR3N1XHdLgDx2dIxFLiX72Otm44jUifJK1VtW-uYzA.